name: merge

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  main-to-published:
    runs-on: ubuntu-24.04
    if: github.repository_owner == 'docker'
    steps:
      - uses: actions/checkout@v4
        with:
          ref: published
      - name: Reset published Branch
        run: |
          git fetch origin main:main
          git reset --hard main
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@d121e62763d8cc35b5fb1710e887d6e69a52d3a4
        with:
          delete-branch: false
          branch: published-update
          commit-message: publish updates from main
          labels: area/release
          title: Automated PR - Publish Updates From Main Branch
          body: |
            # Pull Request Description

            Automated Pull Request for Publishing Docs Updates.
            Commit Detail: ${{ github.sha }}